### ISSUE TITLE
alwayson_script - 'sc couple extension' is not in list

### ISSUE THREAD

**Issue by TheOctonaut** [Chaest/sd-webui-sc-loader#5]
Hi, I am trying to use the bundled next_to_each_other scenario, but I get the below ValueError. SC Loader and Automatic1111 are both up to date, and I placed my sc_config and _db in the automatic1111 configs directory, but any location gives the same error. Nothing is generated.

"portait" and "landscape" do not have the issue (they generate appropriate images). So it is just the scenario in misc.yaml that tries to set base_payload.

```
Traceback (most recent call last):
  File "C:\Server\stable-diffusion-webui\extensions\sd-webui-sc-loader\sc_loader\process\bob.py", line 72, in bobing
    txt2img_gallery, generation_info, html_info, html_log = txt2img(payload)
  File "C:\Server\stable-diffusion-webui\extensions\sd-webui-sc-loader\sc_loader\process\sd.py", line 36, in txt2img
    alwayson_script = script_runner.scripts[[script.title().lower() for script in script_runner.scripts].index(script_name.lower())]
ValueError: 'sc couple extension' is not in list
```

**Comment by Chaest** [comment]
Hi @TheOctonaut, the scenario was indeed ill formed, I released a new version can you tell me if it solved the issue?

Thanks :)

**Comment by Chaest** [comment]
I'm closing for now, please reopen if need be.
