### ISSUE TITLE
working examples would go a long way toward making this easier to use

### ISSUE THREAD

**Issue by FilkerZero** [Chaest/sd-webui-sc-loader#6]
Though there are some sample files in place when the extension is installed in Automatic1111, the lack of concrete examples like the ones shown `Readme.md`, would go a long way toward explaining what some of the elements actually are supposed to represent.  For example, what is the {"pre", "", "post"} in the character entries within a scenario? This is just one of the many things I have not yet worked out, and I've been unable to use this with the current level of documentation.  Web searches for example scenarios has lead me nowhere.  Something as "simple" as two characters interacting across 5 or 6 panels.

**Comment by Chaest** [comment]
Hello,

Thank you for the feedback!

"pre" and "post" are explained here: https://github.com/Chaest/sd-webui-sc-loader/blob/master/docs/scenario_creation.md#prompts

If this is not clear enough, I guess I'll provide better explanation. The documentation must be updated anyway.

To clarify, pre and post are part of prompt that will surround the prompt of the character, that'll give something like: "[sc pre], [char prompt], [sc post]"

I released version 5.3.1 with a page example that should be working. Can you please let me know if it works fine for you/if it helps better understand how it works?

**Comment by Chaest** [comment]
I'm closing unanswered issue after a week. If my modifications do not suit your need please reopen this issue and comment on it.
Thanks
