### ISSUE TITLE
Error during webui startup - "TypeError: cannot unpack non-iterable OutputPanel object"

### ISSUE THREAD

**Issue by FilkerZero** [Chaest/sd-webui-sc-loader#7]
Recently, I started getting the following error traceback on the "Automatic1111 webui" console output in Windows 11:
```
*** Error executing callback ui_tabs_callback for D:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-sc-loader\scripts\main.py
    Traceback (most recent call last):
      File "D:\Automatic1111\stable-diffusion-webui\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "D:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-sc-loader\sc_loader\ui\sc_loader\__init__.py", line 85, in build
        txt2img_gallery, generation_info, html_info, html_log = self.build_components()
    TypeError: cannot unpack non-iterable OutputPanel object

---
```
I don't know if this affects anything, but it wasn't happening in the past.  I did update my Automatic1111 to the latest (`git pull`) and rebuilt my `stable-diffusion-webui\venv`.

**Comment by Chaest** [comment]
Sorry for not answering earlier, I did not see the notification.

Because a recent update of A1111 completely messed up composable LoRA I stopped updating a while ago. Given your error, they changed the output of `create_output_panel` from a tuple to a specific type. I'll try and fix that asap

**Comment by Chaest** [comment]
This should be fixed. Can you check?

For anyone having an issue because you stay in a previous version, you can go to the extension folder and run the command: `git checkout pre-1.8.0-compat` (or 6.0-rc if you want the in dev features)

**Comment by FilkerZero** [comment]
> This should be fixed. Can you check?
> 
> For anyone having an issue because you stay in a previous version, you can go to the extension folder and run the command: `git checkout pre-1.8.0-compat` (or 6.0-rc if you want the in dev features)

It appears to work.  Thanks!

**Comment by Chaest** [comment]
Great, closing the issue then. Don't hesitate if anything else comes up :)
